version: '3.3'

services: 

  product-service:
    build:
      context: ./products
    ports:
      - "8001:3000"
    networks: 
      - microservices
    volumes:
      - ./products/:/app

  review-service:
    build:
      context: ./reviews
    ports:
      - "8002:3000"
    networks:
      - microservices
    volumes:
      - ./reviews/:/app

  api:
    build:
      context: ./api
    ports:
      - "8000:3000"
    networks:
      - microservices
    volumes:
      - ./api/:/app

networks: 
  microservices:
